### ISSUE TITLE
no task in certain bmi3d experiments

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/analyze#59]
laser only task doesn't have a 'task' table because there is nothing to record (cursor, e.g.)
but this table is currently required by proc_exp

```
Traceback (most recent call last):
  File "<ipython-input-18-3c406b9e20ab>", line 19, in <module>
    aopy.preproc.proc_exp(data_dir, files, subj_dir, result_filename, overwrite=True)
  File "/home/aolab/leo/analyze/aopy/preproc.py", line 1104, in proc_exp
    bmi3d_data, bmi3d_metadata = parse_bmi3d(data_dir, files)
  File "/home/aolab/leo/analyze/aopy/preproc.py", line 634, in parse_bmi3d
    data, metadata = _parse_bmi3d_v0(data_dir, files)
  File "/home/aolab/leo/analyze/aopy/preproc.py", line 667, in _parse_bmi3d_v0
    bmi3d_task, bmi3d_task_metadata = load_bmi3d_hdf_table(data_dir, bmi3d_hdf_filename, 'task')
  File "/home/aolab/leo/analyze/aopy/data.py", line 562, in load_bmi3d_hdf_table
    raise ValueError(f"{table_name} not found in {filename}")
ValueError: task not found in /data/raw/hdf/test20210608_11_te1796.hdf
```

**Comment by leoscholl** [comment]
this is a problem again, for trying to record resting state data i am using a bmi3d task with no "task" table.
